"use client";
import { useEffect, useRef, useState } from "react";
import { AlertTriangle, MapPinned } from "lucide-react";
import type { Candidate } from "@/lib/types";

declare global { interface Window { kakao?: { maps: { load: (cb:()=>void)=>void; LatLng: new(lat:number,lng:number)=>unknown; Map: new(el:HTMLElement,opts:unknown)=>{setCenter:(pos:unknown)=>void}; Marker: new(opts:unknown)=>{setMap:(map:unknown)=>void}; CustomOverlay: new(opts:unknown)=>{setMap:(map:unknown)=>void} } } } }

export function KakaoMap({candidates,focused,onFocus}:{candidates:Candidate[];focused:string|null;onFocus:(id:string)=>void}){
 const ref=useRef<HTMLDivElement>(null); const mapRef=useRef<unknown>(null); const key=process.env.NEXT_PUBLIC_KAKAO_MAP_JS_KEY; const [status,setStatus]=useState<"loading"|"ready"|"missing"|"error">(key?"loading":"missing");
 useEffect(()=>{if(!key)return; if(!ref.current)return; let cancelled=false; const init=()=>{window.kakao?.maps.load(()=>{if(cancelled||!ref.current||!window.kakao)return; try{const first=candidates[0]; const center=new window.kakao.maps.LatLng(first?.latitude||37.5665,first?.longitude||126.978); mapRef.current=new window.kakao.maps.Map(ref.current,{center,level:5}); candidates.forEach((candidate,index)=>{const pos=new window.kakao!.maps.LatLng(candidate.latitude,candidate.longitude); const marker=new window.kakao!.maps.Marker({position:pos}); marker.setMap(mapRef.current); const node=document.createElement("button"); node.className=`real-map-label ${focused===candidate.id?"focused":""}`; node.type="button"; node.textContent=`${index+1} ${candidate.name}`; node.onclick=()=>onFocus(candidate.id); new window.kakao!.maps.CustomOverlay({position:pos,content:node,yAnchor:1.8}).setMap(mapRef.current);}); setStatus("ready");}catch{setStatus("error");}})}; if(window.kakao) init(); else {const script=document.createElement("script");script.src=`https://dapi.kakao.com/v2/maps/sdk.js?appkey=${encodeURIComponent(key)}&autoload=false`;script.async=true;script.onload=init;script.onerror=()=>setStatus("error");document.head.appendChild(script);} return()=>{cancelled=true};},[key,candidates,focused,onFocus]);
 useEffect(()=>{const target=candidates.find(c=>c.id===focused); if(target&&mapRef.current&&window.kakao){(mapRef.current as {setCenter:(p:unknown)=>void}).setCenter(new window.kakao.maps.LatLng(target.latitude,target.longitude));}},[focused,candidates]);
 return <div className="map-surface"><div ref={ref} className="kakao-map" aria-hidden={status!=="ready"}/>{status!=="ready"&&<div className="map-fallback"><div className="map-grid"/><span className="map-river"/><div className="fallback-message">{status==="loading"?<><MapPinned/><strong>지도를 불러오는 중입니다</strong><p>후보 목록은 먼저 사용할 수 있습니다.</p></>:status==="missing"?<><MapPinned/><strong>지도 연결 키가 필요합니다</strong><p>후보 목록은 계속 사용할 수 있습니다. Kakao JavaScript 키를 설정하면 지도에 표시됩니다.</p></>:<><AlertTriangle/><strong>지도를 불러오지 못했습니다</strong><p>목록에서 후보를 선택하고 비교할 수 있습니다.</p></>}</div>{candidates.map((candidate,index)=><button key={candidate.id} className={`fallback-pin ${focused===candidate.id?"focused":""}`} style={{left:`${20+(index%3)*27}%`,top:`${28+Math.floor(index/3)*28}%`}} onClick={()=>onFocus(candidate.id)}>{index+1}</button>)}</div>}</div>;
}
